### ISSUE TITLE
Gestion clef SSH

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [ClubInfoPolytechLille/ci-site#9]
_(désordoné)_
- [ ] Générer clef SSH
- [ ] Stocker clef SSH BDD
- [ ] Route
- [ ] UI
- [ ] Révocation clef SSH
- [ ] Ajout/Remplacement clef SSH sur Polytech (requiert #7)
- [ ] Ajout clef SSH sur GitHub (requiert #8)
- [ ] Suppression clef SSH sur GitHub (liste si fail)
